[tool.black]
line-length = 79
target-version = ['py36']
include = '\.pyi?$'
extend-exclude = '''
    face/
'''

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 7
force_single_line = true
extend_skip = [".md", "face/"]

[tool.flake8]
exclude = ".git,__pycache__,.venv,face"
max-complexity = 7

[tool.pytest.ini_options]
testpaths = ['tests']
addopts = '-ra -q'

[tool.coverage.run]
branch = true
source = ['tests']

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'def __repr__',
    'def __str__',
    'raise AssertionError',
    'raise NotImplementedError',
    'if __name__ == .__main__.:',
    '@abstractmethod',
    '@abc.abstractmethod',
    'Enum',
    'IntEnum',
]
